[configuration]
baseline = ['motors', 'shutters', 'mirrors', 'manipulators']

[devices]
i0 = { threshold = 0.1, description = "Gold Mesh" }
i1 = { threshold = 0.15, description = "Back Dioide" }
sc = { threshold = 0.1 }
ref = { threshold = 0.1 }
psh7 = { default = true }

[detectors.alignment]
indirect = "i1"
direct = "sc"

[detectors_sets.default]
primary = ["sc", "tes"]
normalization = "i0"
reference = "ref"

[settings]
modules = ["ucal.startup"]