[configuration]
baseline = ['motors', 'shutters', 'mirrors', 'manipulators']
has_slits = true
has_motorized_samples = true
has_motorized_eref = true

[devices]
i0 = { threshold = 0.1, description = "Gold Mesh" }
i1 = { threshold = 0.15, description = "Back Dioide" }
sc = { threshold = 0.1 }
ref = { threshold = 0.1 }
psh7 = { default = true }

[detectors.alignment]
indirect = "i1"
direct = "sc"

[detectors_sets.default]
primary = ["sc", "tes"]
normalization = "i0"
reference = "ref"

[settings]
modules = ["ucal.startup"]
regions = ["regions.toml"]

[settings.redis]
host = "info.sst.nsls2.bnl.gov"
prefix = "nexafs-"