[configuration]
baseline = ['motors', 'shutters', 'mirrors', 'manipulators']
has_slits = true
has_motorized_samples = true
has_motorized_eref = true

[devices]
i0 = { threshold = 0.1, description = "Gold Mesh" }
i1 = { threshold = 0.15, description = "Back Dioide" }
sc = { threshold = 0.1 }
ref = { threshold = 0.1 }
ucal_sc = { activate = false }
psh7 = { default = true }
ring_current = { baseline = true }
adr = { baseline = true }

[detectors.alignment]
indirect = "i1"
direct = "sc"

[detectors_sets.default]
primary = ["sc", "tes"]
normalization = "i0"
reference = "ref"

[settings]
modules = ["ucal.startup"]
tes_processing = "/nsls2/data/sst/shared/config/ucal/processing_status"

[settings.plans]
xas = ["regions.toml"]

[settings.redis.md]
host = "info.sst.nsls2.bnl.gov"
prefix = "nexafs-"

[settings.redis.info]
host = "info.sst.nsls2.bnl.gov"
prefix = "nexafs-"
port = 60737
db = 4