[gui]
header = "sst-gui-header"

[gui.tabs]
include = ["nbs-gui-queue", "nbs-gui-monitor", "nbs-gui-console", "kafka-table-tab", "ucal-tes-tab", "sst-gui-samples"]

[gui.plans]
include = ["nbs-gui-scan", "nbs-gui-move", "nbs-gui-xas", "nbs-gui-timescan", "nbs-gui-varscan", "nbs-gui-flyscan", "ucal-tes-cal", "ucal-tes-setup", "nbs-gui-samplemove"]


[models.beamline]
primary_energy = "en"
primary_manipulator = "manipulator"
loader = "nbs_bl.qt.models.beamline.SSTBeamlineModel"

[devices]
i0mir = { exclude = true }
psh8 = { visible = false }
psh1 = { visible = false, view_only = true }
en = { "_role" = "energy", "load_order" = 1 }
tes = { "_group" = "misc" }

[loaders]
NewEnPos = "sst_base.qt.models.energy.SST1EnergyModel"
EnPosFactory = "sst_base.qt.models.energy.SST1EnergyModel"
ManipulatorBuilderNEXAFS = "nbs_gui.models.PseudoPositionerModel"
MultiMeshBuilder = "nbs_gui.models.PseudoPositionerModel"
PrettyMotorFMBO = "nbs_gui.models.MotorModel"
PrettyMotor = "nbs_gui.models.MotorModel"
EpicsSignalRO = "nbs_gui.models.PVModelRO"
EpicsSignal = "nbs_gui.models.PVModel"
ShutterSet = "nbs_gui.models.GVModel"
EPS_Shutter = "nbs_gui.models.GVModel"
ADCBuffer = "nbs_gui.models.ScalarModel"
FMBHexapodMirror = "nbs_gui.models.MotorTupleModel"
TESMCAFactory = "ucal.qt.models.tesModel.TESModel"


[kafka]
config_file = "/etc/bluesky/kafka.yml"
bl_acronym = "ucal"