[[catalog]]
label = "NEXAFS Catalog Data"
url = "https://tiled.nsls2.bnl.gov"
catalog_keys = ["ucal", "raw"]
catalog_model = "nbscatalog"


[[catalog]]
label = "NEXAFS Live Data"
source_type = "kafka"
config_file = "/etc/bluesky/kafka.yml"
beamline_acronym = "ucal"
autoload = true